"""add_baseline_mean_to_anomalies

Revision ID: a1b6be44fc72
Revises: 0001
Create Date: 2026-05-27 22:17:07.302606

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "a1b6be44fc72"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anomalies", sa.Column("baseline_mean", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anomalies", "baseline_mean")
    # ### end Alembic commands ###
